version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2019

#Before the build starts
before_build:
- cmd: dotnet restore ./Inshapardaz.Database.sln

# Building
build_script:
  - cmd: dotnet build src/Inshapardaz.Database.Migrations/Inshapardaz.Database.Migrations.csproj
