version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2019


environment:
  ConnectionStringTest:
    secure: xRPJOkFVcWlOPF0wlbbRsjmPXiDSnTjd03Q4aM6bI1hjzjjUsH4wxNSJRnuH3DT9Z3x+fGXmdVdgexKx/ghFpC6znjlEgoE8gL00q86zZ+xcE3piP/6IfH8YutYJ5+OdgOS027eYbt2Ao+LmoZyjy1bGEr3af8wr1NwJrhsHshuzlNrUIpLZ4rbjuMqfiNofNLACeTJ5pif6Z00v2pSRLyEz9QnemZdtwM+zKV9IURTB9UHJFPf36DeaaVU6LCCDMMUCbgVcr1R8rxTnl2UgXZKqX7Q33/Gb2A6VEf/bm7OaqWmr/xAKRzgvInnEcftT
  ConnectionString:
    secure: 77HcU2a57ZxP00HyoA80j3nY9GGcSdBuuUoyj81g+Dc1uzwuINWvzj6NcgMOAf16maRocp7N3lrgTInM8Ep+r+2s1yRx1tPojXTWlBYJVUah8kQKH1IEW7uZBq4L6Vga7dh8CRSuWh8YNVRczFTxAw==

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - cmd: dotnet restore ./Inshapardaz.Database.sln

build_script:
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release .\src\Inshapardaz.Database.Migrations\Inshapardaz.Database.Migrations.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
  - cmd: dotnet run --project .\src\Inshapardaz.Database.Migrations.Runner\Inshapardaz.Database.Migrations.Runner.csproj -- -c "%ConnectionStringTest%"
  - cmd: dotnet run --project .\src\Inshapardaz.Database.Migrations.Runner\Inshapardaz.Database.Migrations.Runner.csproj -- -c "%ConnectionString%"

artifacts:
- path: '**\*.nupkg'
  name: NugetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: g5rGKvlzjcj1STw/jccuiFt+PUh9GBhQaAVBansGo0QNWclKuHVs33Gv3xoYekxR
    artifact: /.*\.nupkg/