DROP TABLE VersionInfo;

DROP TABLE Library.BookCategory;
DROP TABLE Library.SeriesCategory;
DROP TABLE Library.BookFile;
DROP TABLE Library.BookPage;
DROP TABLE Library.ChapterContent;
DROP TABLE Library.Chapter;
DROP TABLE Library.RecentBooks;
DROP TABLE Library.FavoriteBooks;
DROP TABLE Library.ArticleText;
DROP TABLE Library.Article;
DROP TABLE Library.Issue;
DROP TABLE Library.Periodical;
DROP TABLE Library.PeriodicalCategory;
DROP TABLE Library.Book;
DROP TABLE Library.Author;
DROP TABLE Library.Category;
DROP TABLE Library.Series;
DROP TABLE Inshapardaz.[File];
DROP SCHEMA Library
DROP SCHEMA Inshapardaz;